name: get_it_injector
description: >-
  Automate class registration for dependency injection using `get_it`,
  Simplify and manage dependencies effortlessly in Dart projects.

homepage: https://github.com/Couchsurfing/dart-get-it-injector
repository: https://github.com/Couchsurfing/dart-get-it-injector
issue_tracker: https://github.com/Couchsurfing/dart-get-it-injector/issues

topics: [dependency-injection, get-it, code-generation]

version: 0.6.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"

dev_dependencies:
  equatable: ^2.0.7
  lints: ">=3.0.0"
  test: ^1.25.14
