name: get_it_injector_gen
description: >-
    Automate class registration for dependency injection using `get_it`,
    Simplify and manage dependencies effortlessly in Dart projects.
version: 0.1.0
environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    analyzer: '>=5.0.0 <7.0.0'
    build: ^2.4.1
    change_case: ^2.0.1
    code_builder: ^4.9.0
    dart_style: ^2.3.4
    get_it_injector: '>=0.1.0 <1.0.0'
    get_it_injector_core: '>=0.1.0 <1.0.0'
    equatable: '>=2.0.0 <3.0.0'
    glob: ^2.1.2
    json_annotation: ^4.8.1
    meta: '>=1.0.0 <2.0.0'
    source_gen: ^1.4.0

dev_dependencies:
    bloc: ^8.1.2
    build_runner: ^2.4.7
    build_test: ^2.2.1
    derry: ^1.5.0
    generator_test: ^0.3.1
    json_serializable: ^6.7.1
    lints: ^3.0.0
    test: ^1.24.9

dependency_overrides:
    get_it_injector:
        git:
            url: https://github.com/Couchsurfing/dart-get-it-injector
            path: get_it_injector
    get_it_injector_core:
        git:
            url: https://github.com/Couchsurfing/dart-get-it-injector
            path: get_it_injector_core

scripts: ../scripts.yaml
