name: _application
publish_to: 'none'

environment:
    sdk: '>=2.17.0 <4.0.0'

dependencies:
    get_it_injector:
    get_it: ^7.6.6
    _domain:
        path: ../domain

dev_dependencies:
    build_runner: ^2.4.7
    get_it_injector_gen:

dependency_overrides:
    get_it_injector:
        path: ../../../get_it_injector
    get_it_injector_gen:
        path: ../../../get_it_injector_gen
